// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateReceipt(arg1) {
  return window['go']['main']['App']['CreateReceipt'](arg1);
}

export function GetAllSchools() {
  return window['go']['main']['App']['GetAllSchools']();
}

export function GetAllShops() {
  return window['go']['main']['App']['GetAllShops']();
}

export function GetNextControlNumber(arg1) {
  return window['go']['main']['App']['GetNextControlNumber'](arg1);
}

export function UpdateShopBySlug(arg1) {
  return window['go']['main']['App']['UpdateShopBySlug'](arg1);
}
