// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {excel} from '../models';
import {setting} from '../models';

export function AutoMoveBookOrder(arg1:string,arg2:string):Promise<void>;

export function CMDOpenFile(arg1:string):Promise<void>;

export function CreateProcurement(arg1:main.CreateProcurementParams):Promise<string>;

export function CreateReceipt(arg1:main.CreateReceiptParams):Promise<string>;

export function GetAllCustomers():Promise<Array<model.Customer>>;

export function GetAllShops():Promise<Array<model.Shop>>;

export function GetBookOrderFromDataSourceFile(arg1:string):Promise<Array<excel.PublisherItem>>;

export function GetControlData(arg1:string,arg2:number):Promise<excel.ControlDataWithRowCoordinate>;

export function GetNextControlNumber(arg1:string):Promise<number>;

export function GetSetting():Promise<setting.Setting>;

export function GetUseRemoteCustomerDB():Promise<boolean>;

export function OpenDBFileDialog():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenExcelFileDialog():Promise<string>;

export function ResetupApp():Promise<void>;

export function RevertToDefaultCustomerDB():Promise<void>;

export function SaveSetting(arg1:setting.Setting):Promise<void>;

export function UpdateShopBySlug(arg1:model.Shop):Promise<model.Shop>;
