// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoMoveBookOrder(arg1, arg2) {
  return window['go']['main']['App']['AutoMoveBookOrder'](arg1, arg2);
}

export function CMDOpenFile(arg1) {
  return window['go']['main']['App']['CMDOpenFile'](arg1);
}

export function CreateProcurement(arg1) {
  return window['go']['main']['App']['CreateProcurement'](arg1);
}

export function CreateReceipt(arg1) {
  return window['go']['main']['App']['CreateReceipt'](arg1);
}

export function GetAllCustomers() {
  return window['go']['main']['App']['GetAllCustomers']();
}

export function GetAllShops() {
  return window['go']['main']['App']['GetAllShops']();
}

export function GetBookOrderFromDataSourceFile(arg1) {
  return window['go']['main']['App']['GetBookOrderFromDataSourceFile'](arg1);
}

export function GetNextControlNumber(arg1) {
  return window['go']['main']['App']['GetNextControlNumber'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenExcelFileDialog() {
  return window['go']['main']['App']['OpenExcelFileDialog']();
}

export function UpdateShopBySlug(arg1) {
  return window['go']['main']['App']['UpdateShopBySlug'](arg1);
}
