// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function CreateReceipt(arg1:main.CreateReceiptParams):Promise<void>;

export function GetAllSchools():Promise<Array<model.School>>;

export function GetAllShops():Promise<Array<model.Shop>>;

export function GetNextControlNumber(arg1:string):Promise<number>;

export function UpdateShopBySlug(arg1:model.Shop):Promise<void>;
